[package]
name = "marquee"
version = "0.1.0"
authors = ["Merry Mou <moumerry@gmail.com>"]
edition = "2018"

[dependencies]
rpi-led-matrix={path="./../../others/rust-rpi-rgb-led-matrix"}
rosc = "~0.1"
